/**
 * The companion site — improvement #78.
 *
 * `site/book/**` and `sidebar.json` are both generated by `scripts/build-site.ts` and both
 * gitignored. Nothing in this directory is hand-written except this file and `index.md`,
 * so the site cannot drift from the manuscript: it is rebuilt from it every time.
 */
import { defineConfig } from "vitepress";
import sidebar from "./sidebar.json" with { type: "json" };

const DESCRIPTION =
  "The free companion to The Senior Full Stack Handbook — 1,024 interview questions, " +
  "the glossary, and one sample chapter from every part.";

export default defineConfig({
  title: "The Senior Full Stack Handbook",
  description: DESCRIPTION,
  lang: "en-GB",
  cleanUrls: true,
  lastUpdated: true,

  head: [
    ["meta", { property: "og:title", content: "The Senior Full Stack Handbook" }],
    ["meta", { property: "og:description", content: DESCRIPTION }],
    ["meta", { name: "twitter:card", content: "summary_large_image" }],
  ],

  themeConfig: {
    nav: [
      { text: "Read", link: "/book/front/preface" },
      { text: "Questions", link: "/book/back/interview-question-index" },
      { text: "Glossary", link: "/book/back/glossary" },
      { text: "Buy the book", link: "https://leanpub.com/" },
    ],

    sidebar: { "/book/": sidebar },

    outline: [2, 3],
    search: { provider: "local" },

    editLink: undefined,
    footer: {
      message: "Sample chapters and reference material. The full book is on Leanpub.",
      copyright: "© Salman Rahman",
    },
  },

  // The manuscript links to chapters the site deliberately does not publish, and
  // `build-site.ts` rewrites those to /book/. Anything still dead is a real fault.
  ignoreDeadLinks: false,
});
