/**
 * The web edition — improvement #78, the whole book since BOOK-SPEC decision #24.
 *
 * `site/book/**` and `sidebar.json` are both generated by `scripts/build-site.ts` and both
 * gitignored. Nothing in this directory is hand-written except this file, `index.md` and
 * `building-this-book.md` (web only — `site/` is in EXCLUDED_DIRS, so no PDF or EPUB has it),
 * so the site cannot drift from the manuscript: it is rebuilt from it every time.
 *
 * It is served at www.salmanrahman.com/handbook/: the portfolio rewrites that path to this
 * site's own Vercel project, which redeploys on every push to main (`vercel.json`).
 */
import { defineConfig } from "vitepress";
import { withMermaid } from "vitepress-plugin-mermaid";
import sidebar from "./sidebar.json" with { type: "json" };

const BASE = "/handbook/";

const DESCRIPTION =
  "The Senior Full Stack Handbook, free to read online: nine parts, 903 pages in print, and " +
  "Book 2: DSA Patterns — every chapter, 734 interview questions and the glossary.";

export default withMermaid(
  defineConfig({
    title: "The Senior Full Stack Handbook",
    description: DESCRIPTION,
    lang: "en-GB",
    base: BASE,
    cleanUrls: true,
    lastUpdated: true,

    head: [
      // The portfolio's own icons, copied into site/public/ — VitePress does not prefix
      // `head` links with `base`, so the path is written out.
      ["link", { rel: "icon", href: `${BASE}favicon.ico`, sizes: "any" }],
      ["link", { rel: "icon", type: "image/svg+xml", href: `${BASE}icon.svg` }],
      ["meta", { property: "og:title", content: "The Senior Full Stack Handbook" }],
      ["meta", { property: "og:description", content: DESCRIPTION }],
      ["meta", { name: "twitter:card", content: "summary_large_image" }],
    ],

    // VitePress wants the base inside the hostname, or every sitemap URL drops /handbook.
    sitemap: { hostname: `https://www.salmanrahman.com${BASE}` },

    themeConfig: {
      nav: [
        { text: "Read", link: "/book/front/preface" },
        { text: "Contents", link: "/book/" },
        { text: "Questions", link: "/book/back/interview-question-index" },
        { text: "Glossary", link: "/book/back/glossary" },
        { text: "How it's built", link: "/building-this-book" },
        { text: "salmanrahman.com", link: "https://www.salmanrahman.com/" },
      ],

      sidebar: { "/book/": sidebar },

      outline: [2, 3],
      search: { provider: "local" },

      editLink: undefined,
      footer: {
        message: "The whole book, free to read. Generated from the manuscript on every change.",
        copyright: "© Salman Rahman",
      },
    },

    ignoreDeadLinks: false,
  }),
);
